src/components/PreviewProfile/index.tsx, src/components/SmallProfileImage/index.tsx
=> feat(components): improved code styles

package.json, public/assets/approve-icon.svg, public/assets/filter-options-icon.svg, src/components/DropDown/index.tsx, src/components/Table/index.tsx, src/index.ts, src/scss/components/DropDown/_dropdown.scss, src/scss/components/Table/_table.scss, src/scss/styles.scss, src/stories/DropDown.stories.tsx, src/stories/Table.stories.tsx, yarn.lock
- Resolve #55 
- Resolve #128
1. Run project
Now:
=> feat(table): add filters

.changeset/thin-spiders-tickle.md, src/components/Table/index.tsx, src/stories/LendBorrow.stories.tsx, src/stories/Table.stories.tsx
=> fix(table): update optional filters

.changeset/friendly-crews-invent.md, public/assets/approve-icon.svg, src/components/DropDown/index.tsx, src/components/Table/index.tsx, src/stories/Table.stories.tsx
- Resolve #91 
1. Run yarn storybook
2. Check changes:
Now:
=> fix(table): update filters selected by onchange

.changeset/wise-spoons-sleep.md, src/components/Input/index.tsx, src/components/Table/index.tsx
=> fix(lendBorrow): state NaN remove

src/components/BarChart/index.tsx, src/stories/BarChart.stories.tsx
=> fix(components): applied formater XAxis to barchart component

package.json, src/components/Input/index.tsx, src/components/LendBorrow/index.tsx
=> fix(input): improved formater logic

package.json, src/components/BarChart/index.tsx, src/components/ChartContainer/index.tsx, src/components/LineChart/index.tsx, src/scss/components/BarChart/_barChart.scss
=> feat(components): improved barchart component

package.json, src/components/BarChart/index.tsx, src/scss/components/BarChart/_barChart.scss
=> feat(components): improved styles on barchart

package.json, src/components/LendBorrow/index.tsx, src/scss/components/Pill/_pill.scss, src/stories/LendBorrow.stories.tsx
=> feat(components): improved components styles

package.json, src/components/Table/index.tsx, src/stories/Table.stories.tsx
=> fix(table): improved management row onclick action

package.json, src/components/LineChart/index.tsx
=> fix(linegrapich): fixed management big amounts

package.json, src/components/LineChart/index.tsx, src/scss/components/BarChart/_barChart.scss, src/scss/components/LineChart/_lineChart.scss, src/scss/styles.scss
=> fix(linechart): improved bigger amounts management

package.json, src/components/LineChart/index.tsx, yarn.lock
=> fix(linechart): fixed broken styles

package.json, src/components/LineChart/index.tsx
=> fix(linechart): fixed logic to asigned lines color

.changeset/swift-panthers-repair.md, src/components/Tooltip/index.tsx, src/components/Tooltip/useTooltipState.tsx, src/stories/Tooltip.stories.tsx
- Resolve #128
1. Run project
Now:
=> fix(tooltip): add missing font family parameter

.changeset/smart-apples-guess.md, src/components/Tooltip/index.tsx
- Resolve #issueNumber
1. Run project
=> feat(Tooltip): add open parameter

package.json, src/components/CollateralSection/index.tsx, src/components/LendBorrow/index.tsx, src/scss/components/CollateralSection/_collateralSection.scss, src/scss/components/LendBorrow/_lendBorrow.scss, src/scss/styles.scss, src/stories/CollateralSection.stories.tsx, src/stories/LendBorrow.stories.tsx, yarn.lock
=> fix(LendBorrow): fixed styles and improved component interactions

.changeset/warm-houses-approve.md, src/components/BarChart/index.tsx, src/components/BarChart/useBarChartState.tsx
- Resolve #139
1. Run project
Before:
Now:
=> feat(barChart): add checkbox filter

.changeset/ten-ways-play.md, src/components/PieChart/index.tsx, src/stories/Dashboard.stories.tsx, src/stories/PieChart.stories.tsx
- Resolve #144 
1. Run project
Now :
=> fix(pieChart): associate colors to name

package.json, src/components/PieChart/index.tsx, src/scss/components/PieChart/_pieChart.scss, yarn.lock
=> feat(piechart): improved styles on xlarge screens

package.json, src/components/LendBorrow/index.tsx
=> fix(LendBorrow): fixed tabselector load

package.json, src/components/ChartContainer/index.tsx, src/components/LineChart/index.tsx, src/scss/components/Dashboard/_dashboard.scss, src/stories/Dashboard.stories.tsx
- Resolve #167
- Resolve #168
- Resolve #170
=> fix(linechart): fixed linechart component styles

package.json, src/scss/components/Dashboard/_dashboard.scss
=> fix(linechart): adjust checkbox position on mobile

.changeset/late-crews-count.md, public/assets/chevron_left.svg, public/assets/chevron_right.svg, src/components/Table/index.tsx, src/scss/components/Table/_table.scss, src/stories/Table.stories.tsx
- Resolve #156 
- Resolve #174
1. Run project
Before:
Now:
=> feat(table): update page selector

.changeset/lovely-ligers-love.md, src/components/Tooltip/TooltipTypes.ts, src/components/Tooltip/index.tsx
- Resolve #182 
1. Run project
=> fix(tooltip): add default icon

.changeset/wild-bees-shake.md, src/scss/components/Table/_table.scss
- Resolve #186 
1. Run project
=> fix(table): update pagination styles

.changeset/wise-moose-wink.md, src/components/CardComponent/CardComponentTypes.ts, src/components/CardComponent/index.tsx, src/components/InformativeContainer/InformativeContainerTypes.ts, src/components/InformativeContainer/index.tsx, src/index.ts, src/scss/components/CardContainer/_cardContainer.scss, src/scss/components/InformativeContainer/_informativeContainer.scss, src/scss/styles.scss, src/stories/CardComponent.stories.tsx, src/stories/Dashboard.stories.tsx, src/stories/InformativeContainer.stories.tsx
=> feat(Container): add new container

.changeset/clever-masks-rush.md, src/scss/components/Dashboard/_dashboard.scss, src/scss/components/Table/_table.scss
- Resolve #191
- Resolve #197 
1. Run `yarn storybook`
2. Review changes of the pagination component
Before:
Now:
=> fix(table): fixed broken styles on mobile 

.changeset/unlucky-kangaroos-give.md, src/components/CardComponent/index.tsx, src/components/Dashboard/DashboardTypes.ts, src/components/Dashboard/index.tsx, src/scss/components/Dashboard/_dashboard.scss, src/scss/components/InformativeContainer/_informativeContainer.scss, src/stories/Dashboard.stories.tsx
- Resolve #193 
1. Run `yarn storybook`
2. Review changes to the implementation of dashboard stories  
Before:
Now:
=> fix(cardComponent): update styles and stories

README.md
=> Add defactor logo to readme

.changeset/stupid-ways-brake.md, src/components/Table/TableTypes.ts, src/components/Table/index.tsx, src/stories/Table.stories.tsx
=> fix(table): add handle on click page number

package.json, src/components/Dashboard/DashboardTypes.ts, src/components/Dashboard/index.tsx
=> fix(dashboard): added param to receive custom icons on component

package.json, src/components/PieChart/index.tsx, src/scss/components/PieChart/_pieChart.scss
=> fix(piechart): fixed labels positions

README.md
- Resolve #216
1. Check changes
=> content(ReadMe): update content

package.json, src/components/BarChart/BarChartTypes.ts, src/components/BarChart/index.tsx, src/components/BarChart/useBarChartState.tsx, src/scss/components/Dashboard/_dashboard.scss
=> fix(barchart): fixed vertical variant styles

package.json, src/components/CardComponent/index.tsx, src/components/ChartContainer/index.tsx, src/components/Dashboard/index.tsx, src/scss/components/Dashboard/_dashboard.scss, src/scss/components/InformativeContainer/_informativeContainer.scss
=> feat(dashboard): improved styles on this component

README.md
- Resolve #222
1. Check changes
=> fix(ReadMe): requested changes

package.json, src/components/LineChart/index.tsx, src/scss/components/Pill/_pill.scss
=> Removed points on linechart component

package.json, src/components/Button/ButtonTypes.ts, src/components/Button/index.tsx, src/components/CardComponent/index.tsx, src/components/Dashboard/DashboardTypes.ts, src/components/Dashboard/index.tsx, src/scss/components/Dashboard/_dashboard.scss, src/scss/components/InformativeContainer/_informativeContainer.scss, src/scss/components/Pill/_pill.scss
=> fix(components): improved dashboard, pill and button component

package.json, src/components/Table/TableTypes.ts, src/components/Table/index.tsx, src/scss/components/Dashboard/_dashboard.scss, src/scss/components/Pill/_pill.scss
=> feat(table): improved table management styles

package.json, src/scss/components/Container/_container.scss, src/scss/components/LendBorrow/_lendBorrow.scss, src/scss/components/Sidebar/_sidebar.scss
=> feat(components): updated shadows styles

.changeset/many-nails-pull.md, src/components/BarChart/index.tsx, src/components/LanguageSelector/index.tsx, src/components/LineChart/index.tsx, src/scss/components/Dashboard/_dashboard.scss, src/stories/LanguageSelector.stories.tsx
- Resolve #242
1. Run project
Now:
=> fix(components): update components and styles

.changeset/great-carrots-sit.md, src/components/LanguageSelector/index.tsx, src/scss/components/LanguageSelector/_languageSelector.scss
- Resolve #246
1. Run project
Before:
Now:
=> fix(LanguageSelector): update styles on mobile version

package.json, src/components/Modal/ModalTypes.ts, src/components/Modal/index.tsx
=> feat(modal): added param to improve styles

package.json, public/assets/close-icon.svg, src/components/LendBorrow/LendBorrowTypes.ts, src/components/LendBorrow/index.tsx, src/scss/components/LendBorrow/_lendBorrow.scss, src/scss/components/Modal/_modal.scss, src/stories/LendBorrow.stories.tsx
=> feat(modal): improved modal component styles

package.json, src/components/BarChart/index.tsx, src/components/CollateralSection/CollateralSectionTypes.ts, src/components/CollateralSection/index.tsx, src/components/LendBorrow/LendBorrowTypes.ts, src/components/LineChart/index.tsx, src/components/PieChart/index.tsx, src/stories/LineChart.stories.tsx
=> feat(charts): updated charts styles

src/components/Button/ButtonTypes.ts, src/components/Button/index.tsx, src/components/CardComponent/CardComponentTypes.ts, src/components/CardComponent/index.tsx, src/components/CardContainer/CardContainerTypes.ts, src/components/CardContainer/index.tsx, src/components/ChartContainer/ChartContainerTypes.ts, src/components/ChartContainer/index.tsx, src/components/Container/ContainerTypes.ts, src/components/Container/index.tsx, src/components/Dashboard/DashboardTypes.ts, src/components/Dashboard/index.tsx, src/components/InformativeContainer/InformativeContainerTypes.ts, src/components/InformativeContainer/index.tsx, src/components/Pill/PillTypes.ts, src/components/Pill/index.tsx, src/components/Sidebar/SidebarTypes.ts, src/components/Sidebar/index.tsx, src/components/Table/TableTypes.ts, src/components/Table/index.tsx, src/stories/Button.stories.tsx, src/stories/CardComponent.stories.tsx, src/stories/CardContainer.stories.tsx, src/stories/Container.stories.tsx, src/stories/Dashboard.stories.tsx, src/stories/InformativeContainer.stories.tsx, src/stories/Pill.stories.tsx, src/stories/Sidebar.stories.tsx, src/stories/Table.stories.tsx
- Resolve #265
1. Run project
Now:
=> feat(styles): add optional styles

src/stories/CustomTooltip.stories.mdx, src/stories/CustomTooltip.stories.tsx, src/stories/Dropzone.stories.tsx, src/stories/TitleWithIcon.stories.mdx
- Resolve #285 
1. yarn install
2. yarn storybook
=> Bug fix 285

src/components/CustomCheckbox/index.tsx, src/index.ts, src/stories/CustomCheckbox.stories.mdx, src/stories/CustomCheckbox.stories.tsx
=> V2 customcheckbox 303

src/components/CardWithHover/index.tsx, src/index.ts, src/stories/CardWithHover.stories.mdx, src/stories/CardWithHover.stories.tsx
=> V2 cardwithhover 308

src/components/CardWithHover/index.tsx, src/components/Icons/v2/copyTemplateIcon.tsx, src/components/Icons/v2/docIcon.tsx, src/components/Icons/v2/plusIcon.tsx, src/index.ts, src/stories/CardWithHover.stories.mdx, src/stories/CardWithHover.stories.tsx
- Resolve #316 
The recent updates to the CardWithHover component include the addition of hover functionality and an icon copy, various style fixes, corrections to properties, enhancements to the onClick functions, testing, fixes, documentation updates, and the export of both a documentation icon and a plus icon.
=> Modify cardwithhover 316

.storybook/global.css, src/themes.ts
- Resolve #306 
Updates Applied to Stylesheets:
- Global CSS Changes:
Imported the 'DM Sans' font from Google Fonts:
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap');
- Theme Configuration Adjustments:
Updated themes.ts to specify the default font family:
fontFamily: '"DM Sans", sans-serif',
**The recent changes have been successfully implemented, and the fonts are now displaying correctly.**
=> fix(Typography): Fixed Fonts. #306

src/components/MainSidebar/index.tsx, src/stories/MainSidebar.stories.tsx
=> fix(MainSidebar): Defaults and activetextcolor. #332

src/components/Dropzone/index.tsx, src/components/Popover/index.tsx
=> fix(storybook): Added TODO-s. #334

.changeset/cyan-sloths-jump.md
- Resolve #339 
Added yarn changeset
=> feat(Conflicts): Added yarn changeset. #339

src/stories/TitleWithIcon.stories.mdx
=> fix(TitleWithIcon): Corrected import in mdx. #342

.changeset/hot-doors-love.md, src/components/CardWithHover/index.tsx, src/components/ChainCard/index.tsx, src/components/CustomCheckbox/index.tsx, src/components/CustomDropdown/index.tsx, src/components/CustomTextField/index.tsx, src/components/CustomTooltip/index.tsx, src/components/Dropzone/index.tsx, src/components/MainCard/index.tsx, src/components/MainSidebar/MenuItem.tsx, src/components/MainSidebar/index.tsx, src/components/Popover/index.tsx, src/components/ResponsiveToggle/StatsBox/index.tsx, src/components/TitleWithIcon/index.tsx, src/stories/CardWithHover.stories.tsx, src/stories/CustomDropdown.stories.tsx, src/stories/CustomTextField.stories.tsx, src/stories/Dropzone.stories.tsx, src/stories/MainCard.stories.tsx, src/stories/MainSidebar.stories.tsx, src/stories/TitleWithIcon.stories.tsx, src/themes.ts
=> Replacing Hardcoded Color Values with Theme Variables 

package.json, src/components/Dashboard/index.tsx, src/components/MultichainSelector/index.tsx, src/stories/Dashboard.stories.tsx
=> feat(multichain): improved styles on Dahboard and multichain selector

.changeset/clever-suns-report.md, src/components/MainSidebar/index.tsx, src/components/MainSidebar/routes.ts, src/stories/MainSidebar.stories.tsx
=> fix(MainSidebar): Fixed path. #380

package.json, src/components/Sidebar/index.tsx
=> feat(sidebar): updated styles

package.json, src/components/Button/ButtonTypes.ts, src/components/PieChart/PieChartTypes.ts, src/components/PieChart/index.tsx, src/scss/components/Button/_button.scss, src/scss/components/PieChart/_pieChart.scss, src/stories/Button.stories.tsx
=> feat(piechart): allow internal content on chart

package.json, src/components/WalletComponent/WalletContainer.tsx, src/components/WalletComponent/WalletSelector.tsx, src/components/WalletComponent/WalletTypes.ts, src/stories/WalletSelector.stories.tsx
=> feat(walletSelector): added multicollateral

package.json, src/components/BarChart/index.tsx, src/components/MobileList/MobileListTypes.ts, src/components/MobileList/index.tsx, src/scss/components/Modal/_modal.scss, src/stories/BarChart.stories.tsx
=> feat(bartchart): Adjusted styles on vertical version

package.json, src/components/CardComponent/index.tsx, src/components/LineChart/index.tsx, src/components/PieChart/PieChartTypes.ts, src/components/PieChart/index.tsx
- Resolve #412
Add a `sx` parameter to the `PieChart` component to allow for custom styling using Material-UI's `SxProps`, update the `CardComponent` to improve text wrapping, and adjust the width of the `LineChart` component.
The `sx` parameter provides developers with more flexibility to customize the appearance of the `PieChart` component, enhancing the UI's adaptability to different design requirements. The text wrapping improvement in `CardComponent` ensures better display of content, and the width adjustment in `LineChart` optimizes its layout within the UI. These changes collectively aim to improve the overall user interface and user experience.
> Is this description stale? Ask me to generate a new description by commenting `/korbit-generate-pr-description`
=> feat(piechart): added param to personalize styles

package.json, src/components/BarChart/index.tsx, src/stories/BarChart.stories.tsx
=> fix(barchart): ajusted large labels on horizontal variant

.changeset/gentle-bulldogs-roll.md, src/index.ts
=> Added props exports

package.json, src/components/LendBorrow/LendBorrowTypes.ts, src/components/LendBorrow/index.tsx, src/stories/LendBorrow.stories.tsx
=> feat(LendBorrow): added min and max elements on this component

.changeset/young-ladybugs-brake.md, src/components/PreviewProfile/PreviewProfileTypes.ts, src/components/PreviewProfile/index.tsx, src/components/SmallProfileImage/SmallProfileImageTypes.ts, src/components/SmallProfileImage/index.tsx
=> Added imageRadius

.changeset/lazy-steaks-rest.md, src/components/MobileMenu/MobileMenuTypes.ts, src/components/MobileMenu/index.tsx
=> Added optional margin prop to MobileMenu

.changeset/fuzzy-experts-pretend.md, .vscode/settings.json, src/components/MainSidebar/index.tsx, src/components/Sidebar/index.tsx
=> Sidebar and MainSidebar: Removed borders and border shadows.

.changeset/wild-planes-bake.md, src/components/Button/ButtonTypes.ts, src/components/Button/index.tsx, src/components/WalletComponent/WalletSelector.tsx, src/components/WalletComponent/WalletTypes.ts
=> Unified Wallet Selector BTN

.changeset/flat-baboons-sniff.md, src/components/MainSidebar/MenuItem.tsx, src/components/MainSidebar/index.tsx, src/stories/MainSidebar.stories.tsx
=> MainSidebar: Added activeBorderColor prop

.changeset/kind-actors-train.md, src/components/MainSidebar/index.tsx
=> Fixed MainSidebar Border and Divider Logics

.changeset/green-tables-warn.md, src/components/MainSidebar/MenuItem.tsx, src/components/MainSidebar/index.tsx
=> Fix MainSidebar Component to Prevent Full Page Refresh on Menu Click

.changeset/twenty-bags-study.md, src/components/V3/ClaimTokensButtonV3/index.tsx, src/stories/ClaimTokensButtonV3.stories.tsx
=> ClaimTokensButtonV3

.changeset/gorgeous-pears-burn.md, src/components/MainSidebar/MenuItem.tsx, src/components/MainSidebar/index.tsx
=> MainSidebar: Border style fixes.

package.json, src/components/LineChart/ChartsTypes.ts, src/components/LineChart/index.tsx
=> feat(linechart): added condition to hide checkbox section

.changeset/heavy-rice-brake.md, public/assets/add-icon.svg, src/components/V3/EmptyTableV3/index.tsx, src/stories/EmptyTableV3.stories.tsx
=> Added Btn and props to EmptyTableV3

.changeset/mean-paws-fetch.md, src/components/V3/EmptyTableV3/index.tsx
=> EmptyTableV3: Fixed fontSize and added color props

.changeset/light-toys-obey.md, src/components/V3/EmptyTableV3/index.tsx
=> EmptyTableV3: Added prop iconBgColor.

.changeset/fuzzy-elephants-matter.md, src/components/CustomDropdown/index.tsx, src/components/CustomTextField/index.tsx, src/components/CustomTooltip/index.tsx
=> Add tooltipBgColor Props

.changeset/slimy-seas-switch.md, src/components/CustomDropdown/index.tsx, src/components/CustomTextField/index.tsx
=> Fixed focused colors

package.json, src/components/LoaderApp/index.tsx
=> feat(loaderApp): added custom label

.changeset/violet-bags-retire.md
=> Added changeset

.changeset/ten-camels-float.md, src/components/Button/ButtonTypes.ts, src/components/Button/index.tsx, src/scss/components/Button/_button.scss, src/stories/Button.stories.tsx
=> Enhance Button Component with Centered Loader and Hidden Text During Loading State

.changeset/odd-weeks-vanish.md, src/components/MultiLineButton/ButtonTypes.ts, src/components/MultiLineButton/index.tsx, src/index.ts, src/stories/MultiLineButton.stories.tsx
=> Add MultiLineButton

.changeset/khaki-icons-run.md, src/components/V3/AreaChartV3/index.tsx
Added a Tooltip component to the AreaChartV3, along with a CustomTooltip function that formats and displays tooltip content when hovering over data points.
- Resolve #549
=> Added a Tooltip component to the AreaChartV3

.changeset/hungry-days-sleep.md, src/components/MultichainSelector/index.tsx, src/stories/MultichainSelector.stories.tsx, src/stories/MultichainSelectorV3.stories.tsx
=>  Styled Multichain component width and applied small fixes to prevent network name cutoff

.changeset/happy-readers-push.md, src/components/MultichainSelector/index.tsx
=> Add padding to MultichainSelector

.changeset/three-buckets-eat.md, src/components/Pagination/index.tsx, src/components/Table/TableTypes.ts, src/components/Table/index.tsx
Added fontSize as prop
- Resolve part of #560
=> Adjusted pagination boxes positions, size, and font size of table elements.

.changeset/nine-chefs-prove.md, src/components/Pagination/index.tsx, src/stories/Table.stories.tsx
=> Ensured rowsPageSelected does not exceed totalRowsNumber

.changeset/large-eagles-argue.md, src/components/Pagination/index.tsx, src/stories/Table.stories.tsx
=> Improve pagination

.changeset/breezy-bags-know.md, src/scss/components/Table/_table.scss
=> Pagination: Change padding

.changeset/spotty-dots-sort.md, src/components/V3/AreaChartV3/index.tsx, src/stories/AreaChartV3.stories.tsx
=>  AreaChartV3: Adjust y-axis domain for constant data values

.changeset/cold-trainers-move.md, src/components/V3/EmptyTableV3/index.tsx
=> Edit EmptyTableV3

.changeset/little-bugs-prove.md, src/components/V3/CustomTabsContainerV3/index.tsx, src/index.ts, src/stories/CustomTabsContainerV3.stories.tsx
=> Add CustomTabsContainerV3

.changeset/giant-horses-learn.md, src/components/V3/CustomTabsContainerV3/index.tsx
=> CustomTabsContainerV3: Added optional width prop

.changeset/mean-jars-try.md, src/components/V3/CustomTabsContainerV3/index.tsx, src/stories/CustomTabsContainerV3.stories.tsx
=> CustomTabsContainerV3: Adjust the component for mobile devices

.changeset/curly-yaks-kick.md, src/components/V3/CustomTabsContainerV3/index.tsx
=>  CustomTabsContainerV3: Add scrollable styles and props

.changeset/honest-falcons-hug.md, src/components/V3/CustomTabsContainerV3/index.tsx, src/stories/CustomTabsContainerV3.stories.tsx
=> CustomTabsContainerV3: Added textActive and textDisabled as props

.changeset/tender-wasps-juggle.md, src/components/Pagination/index.tsx
=> Table Pagination: center show 10 only on @media (max-width: 400px)

.changeset/wise-years-rush.md, src/components/V3/CustomTabsContainerV3/index.tsx
=> CustomTabsContainerV3: Add dividerWidth as prop.

.changeset/hot-seas-repair.md, src/components/V3/CustomTabsContainerV3/index.tsx
=> CustomTabsContainerV3: Adjusted divider width for mobile responsiveness

package.json, src/components/PieChart/index.tsx
=> feat: improved piechart component
